name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{'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'}}

      - name: Snyk Code (SAST)
        run: snyk code test
        continue-on-error: tru

